aa: rand-m9-mstd0.5-inc1
amp: true
batch_size: 64
center_loss_weight: 0.0005
cfg: ./experiments/subnet/AutoFormer-B-ReID.yaml
change_qkv: true
clip_grad: 1.0
color_jitter: 0.4
cooldown_epochs: 10
data_path: /data/ezhe473/datasets/ATRW
data_set: ATRW
device: cuda
dist_backend: nccl
dist_eval: true
dist_url: env://
distributed: true
drop: 0.0
drop_path: 0.1
epochs: 120
eval: true
gp: true
gpu: 0
input_size: 256
label_smooth: 0.1
lr: 0.00035
max_relative_position: 14
min_lr: 1.0e-06
mode: retrain
momentum: 0.9
no_abs_pos: false
num_workers: 8
opt: adamw
opt_eps: 1.0e-08
output_dir: ./output_reid/
patch_size: 16
pin_mem: true
rank: 0
recount: 1
reid_dim: 256
relative_position: true
remode: pixel
reprob: 0.5
resume: /data/ezhe473/CreamOutput/AutoFormer/supernet-tiny.pth
sched: cosine
seed: 0
start_epoch: 0
train_interpolation: bicubic
triplet_margin: 0.3
warmup_epochs: 10
warmup_lr: 1.0e-06
weight_decay: 0.0001
world_size: 1
