amp: true
batch_size: 64
cfg: ./experiments/supernet/supernet-T.yaml
change_qkv: true
crossover_num: 25
data_path: /data/ezhe473/datasets/ATRW
data_set: ATRW
device: cuda
dist_backend: nccl
dist_eval: true
dist_url: env://
distributed: true
epochs: 30
gp: true
gpu: 0
input_size: 256
m_prob: 0.2
max_epochs: 20
max_relative_position: 14
min_param_limits: 5.0
model: ''
mutation_num: 25
no_abs_pos: false
num_workers: 8
output_dir: ./search_output
param_limits: 23.0
patch_size: 16
pin_mem: true
platform: pai
population_num: 50
rank: 0
reid_dim: 256
relative_position: true
resume: /data/ezhe473/CreamOutput/AutoFormer/supernet-tiny.pth
s_prob: 0.4
scale: false
seed: 0
select_num: 10
teacher_model: ''
world_size: 1
